#!/usr/bin/env php
<?php
/**
 * @link http://ipaya.cn/
 * @copyright Copyright (c) 2016 ipaya.cn
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

$composerAutoload = [
    __DIR__ . '/../vendor/autoload.php',
    __DIR__ . '/../../autoload.php',
    __DIR__ . '/vendor/autoload.php',
];

$vendorPath = null;
foreach ($composerAutoload as $autoload) {
    if (file_exists($autoload)) {
        require($autoload);
        $vendorPath = dirname($autoload);
        break;
    }
}

require($vendorPath . '/yiisoft/yii2/Yii.php');

$application = new yii\console\Application([
    'id' => 'iPaya-swoole',
    'basePath' => __DIR__ . '/src',
    'enableCoreCommands' => false,
    'runtimePath' => __DIR__ . '/runtime',
    'controllerNamespace' => 'iPaya\Swoole\Commands',
    'aliases' => [
        '@iPaya/Swoole' => __DIR__ . '/src/'
    ],
    'components' => [
        'mailer' => [
            'class' => 'yii\swiftmailer\Mailer',
            'useFileTransport' => true,
        ],
        'redis' => [
            'class' => 'yii\redis\Connection',
            'hostname' => '127.0.0.1',
            'port' => 6379,
            'database' => 0
        ]
    ]
]);
$application->run();
