#!/usr/bin/env php
<?php
/**
 * @link http://ipaya.cn/
 * @copyright Copyright (c) 2016 ipaya.cn
 */

defined('YII_DEBUG') or define('YII_DEBUG', true);

$composerAutoload = [
    __DIR__ . '/../vendor/autoload.php', // in yii2-dev repo
    __DIR__ . '/../../autoload.php', // installed as a composer binary
];

$vendorPath = null;
foreach ($composerAutoload as $autoload) {
    if (file_exists($autoload)) {
        require($autoload);
        $vendorPath = dirname($autoload);
        break;
    }
}

require($vendorPath . '/yiisoft/yii2/Yii.php');

$application = new yii\console\Application([
    'id' => 'iPaya-swoole',
    'basePath' => __DIR__ . '/src',
    'enableCoreCommands' => false,
    'runtimePath' => __DIR__ . '/runtime',
    'controllerNamespace' => 'iPaya\Swoole\Commands',
    'aliases' => [
        '@iPaya/Swoole' => __DIR__ . '/src/'
    ]
]);
$application->run();
